# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "13c9ee58b0ad16670fd1d78b889af5ab"
name = "product-description-generator"
handle = "product-description-generator-16"
application_url = "https://mg-olympics-actress-file.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://mg-olympics-actress-file.trycloudflare.com/auth/callback", "https://mg-olympics-actress-file.trycloudflare.com/auth/shopify/callback", "https://mg-olympics-actress-file.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
